webapp/ticket_sales/urls.py
from django.urls import path
from .views import TicketSaleListView, TicketSaleUpdateView, TicketSaleDeleteView, \
    TicketSaleDetailView, payment_process_cashier, check_payment_status_cashier, payment_detail_view, \
    ticket_sale_create_view, \
    ticket_sale_update_view, cash_payment_process, print_ticket_view, filtered_events, filtered_event_times, \
    ticket_sales_service_create, ticket_sales_service_update, ticket_sales_service_delete, \
    ticket_sales_payments_create, ticket_sales_payments_update, ticket_sales_payments_delete, \
    filtered_services, get_service_cost, terminal_settings_cashier, register_terminal, refresh_terminal_token, \
    get_events_dates, get_events, TicketSaleUpdateViewTerminal, home_page_terminal, create_ticket_sale_terminal, \
    create_ticket_sale_cashier, payment_process_terminal, check_payment_status_terminal, terminal_settings_terminal, \
    get_refund_tickets, refund_tickets, kiosk_sale_tickets, ticket_sales_booking_list, ticket_sales_booking_create, \
    ticket_sales_booking_update, ticket_sales_booking_delete, tickets_purchased, delete_bookings, get_refund_payments, \
    check_payment_refund_status, bulk_delete_ticket_sales, ticket_sales_create_discount_tickets

app_name = 'ticket_sales'

urlpatterns = [
    path('list/', TicketSaleListView.as_view(), name='ticket-sale-list'),
    path('create/', create_ticket_sale_cashier, name='ticket-sale-create'),
    path('<int:pk>/update/', TicketSaleUpdateView.as_view(), name='ticket-sale-update'),
    path('<int:pk>/delete/', TicketSaleDeleteView.as_view(), name='ticket-sale-delete'),
    path('bulk-delete/', bulk_delete_ticket_sales, name='bulk-delete'),
    path('<int:pk>/', TicketSaleDetailView.as_view(), name='ticket-sale-detail'),
    path('create-x/', ticket_sale_create_view, name='ticket-sale-create-x'),
    path('<int:pk>/update-x/', ticket_sale_update_view, name='ticket-sale-update-x'),
    path('<int:pk>/update-t/', TicketSaleUpdateViewTerminal.as_view(), name='ticket-sale-update-t'),
    path('home-terminal/', home_page_terminal, name='home-terminal'),
    path('kiosk-sale-tickets/<uuid:kiosk_guid>/', kiosk_sale_tickets, name='kiosk-sale-tickets'),
    path('tickets-purchased/<int:sale_id>/', tickets_purchased, name='tickets-purchased'),
    path('create-sale-terminal/', create_ticket_sale_terminal, name='create-sale-terminal'),
    path('delete-bookings/', delete_bookings, name='delete-bookings'),

    # TicketSalesService URLs
    path('<int:ticket_sale_id>/services/create/', ticket_sales_service_create,
         name='ticket-sales-service-create'),
    path('<int:ticket_sale_id>/services/<int:pk>/update/', ticket_sales_service_update,
         name='ticket-sales-service-update'),
    path('<int:ticket_sale_id>/services/<int:pk>/delete/', ticket_sales_service_delete,
         name='service-delete'),

    # TicketSalesPayments URLs
    path('<int:ticket_sale_id>/payments/<int:pk>/detail', payment_detail_view, name='payment-detail'),
    path('<int:ticket_sale_id>/payments/create/', ticket_sales_payments_create, name='payment-create'),
    path('<int:ticket_sale_id>/payments/<int:pk>/update/', ticket_sales_payments_update,
         name='payment-update'),
    path('<int:ticket_sale_id>/payments/<int:pk>/delete/', ticket_sales_payments_delete,
         name='payment-delete'),

    # Payment process
    path('payment-process/<int:ticket_sale_id>/', payment_process_cashier, name='payment-process'),
    path('payment-process-terminal/<int:ticket_sale_id>/', payment_process_terminal, name='payment-process-terminal'),
    path('check-payment-status/<str:process_id>/<str:ticket_sale_id>/<str:expected_amount>',
         check_payment_status_cashier,
         name='check-payment-status'),
    path('check-payment-status-terminal/<str:process_id>/<str:ticket_sale_id>/<str:expected_amount>/',
         check_payment_status_terminal,
         name='check-payment-status-terminal'),
    path('cash-payment-process/<int:ticket_sale_id>/', cash_payment_process, name='cash-payment-process'),

    # Print ticket
    path('ticket-print-data/<int:ticket_sale_id>/', print_ticket_view, name='ticket-print-data'),

    # Filtered events, services
    path('filtered-events/', filtered_events, name='filtered-events'),
    path('filtered-event-times/', filtered_event_times, name='filtered-event-times'),
    path('filtered-services/<str:sale_type>/', filtered_services, name='filtered-services'),
    path('get-service-cost/', get_service_cost, name='get-service-cost'),
    path('get-events-dates/', get_events_dates, name='get-events-dates'),
    path('get-events/', get_events, name='get-events'),

    # Terminal settings
    path('terminal-settings-cashier/', terminal_settings_cashier, name='terminal-settings-cashier'),
    path('terminal-settings-terminal/', terminal_settings_terminal, name='terminal-settings-terminal'),
    path('register-terminal/', register_terminal, name='register-terminal'),
    path('refresh-terminal-token/', refresh_terminal_token, name='refresh-terminal-token'),

    # Возврат билетов
    path('<int:sale_id>/refund-tickets/', get_refund_tickets, name='refund_tickets_list'),
    path('<int:sale_id>/refund-tickets/confirm/', refund_tickets, name='refund_tickets'),
    path('check-refund-status/<str:process_id>/<str:ticket_sale_id>/', check_payment_refund_status,
         name='check-refund-status'),

    # Бронирование билетов
    path('bookings/<uuid:booking_guid>/', ticket_sales_booking_list, name='booking_list'),
    path('bookings/create/', ticket_sales_booking_create, name='booking_create'),
    path('bookings/<int:pk>/edit/', ticket_sales_booking_update, name='booking_update'),
    path('bookings/<int:pk>/delete/', ticket_sales_booking_delete, name='booking_delete'),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views

from references.views import home_page
from .drf_yasg_schema import schema_view

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path("references/", include("references.urls")),
    path("ticket-sales/", include("ticket_sales.urls")),
    path("reports/", include("reports.urls")),

    path('api-token-auth/', views.obtain_auth_token),
    path("api/", include("ticket_sales.api_urls")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', home_page, name='home'),
]

# # Add this to include language prefixes
# urlpatterns += i18n_patterns(
#     path('', HomePageView.as_view(), name='home'),
#     path("news/", include("news.urls")),
# )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/ticket_sales/models.py
from datetime import datetime

from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
import uuid
import enum

from records.models import LoggableModelMixin
from references.models import Service, Event, Inventory
from ticket_sales.helpers import get_num_val


def default_datetime():
    return datetime.now().date()


class SaleTypeEnum(enum.Enum):
    CS = "CS", "Касса"
    TS = "TS", "Киоск"
    SM = "SM", "Сайт muzaidyny.kz"
    KP = "KP", "Kaspi платежи"

    @classmethod
    def choices(cls):
        return [(key.value[0], key.value[1]) for key in cls]


class SaleStatusEnum(enum.Enum):
    NP = "NP", "Не оплачен"
    PD = "PD", "Оплачен"
    PP = "PP", "Частично оплачен"
    RT = "RT", "Возврат"
    PT = "PT", "Частичный возврат"
    CN = "CN", "Отменен"
    IS = "IS", "Оформлен"

    @classmethod
    def choices(cls):
        return [(key.value[0], key.value[1]) for key in cls]


class PaymentMethods(enum.Enum):
    QR = "QR", "Оплата по QR"
    CD = "CD", "Оплата картой"
    CH = "CH", "Наличка"

    @classmethod
    def choices(cls):
        return [(key.value[0], key.value[1]) for key in cls]


class TicketSale(LoggableModelMixin, models.Model):
    date = models.DateField(default=timezone.now, verbose_name="Дата")
    time = models.TimeField(verbose_name="Время", blank=True, null=True)
    amount = models.IntegerField(verbose_name="Сумма итого", blank=True, default=0)
    paid_amount = models.IntegerField(verbose_name="Сумма оплаты", blank=True, default=0)
    refund_amount = models.IntegerField(verbose_name="Сумма возврата", blank=True, default=0)
    paid_cash = models.IntegerField(verbose_name="Оплачено наличкой", blank=True, default=0)
    paid_card = models.IntegerField(verbose_name="Оплачено картой", blank=True, default=0)
    paid_qr = models.IntegerField(verbose_name="Оплачено QR", blank=True, default=0)
    status = models.CharField(max_length=2, verbose_name='Статус',
                              choices=SaleStatusEnum.choices(),
                              null=True,
                              blank=True,
                              default=SaleStatusEnum.NP.value[0])
    tickets_count = models.PositiveSmallIntegerField(verbose_name="Всего билетов", blank=True, default=0)
    sale_type = models.CharField(max_length=2,
                                 verbose_name="Тип продажи",
                                 choices=SaleTypeEnum.choices(),
                                 default='CS',
                                 blank=True)
    email = models.CharField(max_length=50, verbose_name='Email', null=True, blank=True)
    phone = models.CharField(max_length=50, verbose_name='Телефон', null=True, blank=True)
    booking_begin_date = models.DateTimeField(verbose_name="Дата время бронирования", null=True, blank=True)
    booking_end_date = models.DateTimeField(verbose_name="Дата время окончания бронирования", null=True, blank=True)
    booking_guid = models.UUIDField(verbose_name="GUID бронирования", blank=True)

    def __str__(self):
        return f'№{self.pk} от {self.date}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-id']

    def save(self, *args, **kwargs):
        update_date = kwargs.pop('update_date', False)
        if update_date:
            self.date = datetime.now().date()
            self.time = datetime.now().time()

        # Рассчитываем сумму оплаты
        self.paid_amount = get_num_val(self.paid_cash) + get_num_val(self.paid_card) + get_num_val(self.paid_qr)

        # Обновляем статус заказа в зависимости от суммы оплаты и возврата
        update_status = kwargs.pop('update_status', True)
        if update_status: #  and self.status != 'CN' # если заказ не отменен
            if self.paid_amount == 0:
                self.status = SaleStatusEnum.NP.value[0]
            elif self.paid_amount >= self.amount:
                if self.refund_amount > 0:
                    if self.paid_amount > self.refund_amount:
                        self.status = SaleStatusEnum.PT.value[0]
                    else:
                        self.status = SaleStatusEnum.RT.value[0]
                else:
                    self.status = SaleStatusEnum.PD.value[0]
            elif self.paid_amount < self.amount:
                self.status = SaleStatusEnum.PP.value[0]
        super(TicketSale, self).save(*args, **kwargs)


class TicketSalesService(LoggableModelMixin, models.Model):
    ticket_sale = models.ForeignKey(TicketSale, on_delete=models.CASCADE, verbose_name="Заказ")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Услуга")
    event = models.ForeignKey(Event, on_delete=models.PROTECT, verbose_name="Мероприятие")
    event_date = models.DateField(verbose_name="Дата мероприятия", default=default_datetime)
    event_time = models.TimeField(verbose_name="Время начала мероприятия")
    event_time_end = models.TimeField(verbose_name="Время окончания мероприятия", blank=True, null=True)
    tickets_count = models.PositiveSmallIntegerField(verbose_name="Количество билетов")
    tickets_amount = models.IntegerField(verbose_name="Сумма билетов")
    discount = models.IntegerField(verbose_name="Скидка", blank=True, default=0)
    total_amount = models.IntegerField(verbose_name="Сумма итого")
    paid_amount = models.IntegerField(verbose_name="Сумма оплачено", blank=True, default=0)

    def __str__(self):
        return f'{self.ticket_sale.pk}-{self.pk}'

    class Meta:
        verbose_name = 'Услуга заказа'
        verbose_name_plural = 'Услуги заказов'
        ordering = ['-id']


class TicketSalesPayments(LoggableModelMixin, models.Model):
    ticket_sale = models.ForeignKey(TicketSale, on_delete=models.CASCADE, verbose_name="Заказ")
    payment_date = models.DateTimeField(verbose_name="Дата оплаты")
    payment_method = models.CharField(
        max_length=2,
        choices=PaymentMethods.choices(),
        default="QR",
    )
    amount = models.IntegerField(verbose_name="Сумма оплаты", blank=True, default=0)
    refund_amount = models.IntegerField(verbose_name="Сумма возврата", blank=True, default=0)
    process_id = models.CharField(max_length=20, verbose_name='Идентификатор процесса', null=True, blank=True)
    last_status = models.CharField(max_length=15, verbose_name='Последний статус', null=True, blank=True)
    error_text = models.CharField(max_length=450, verbose_name='Текст ошибки', null=True, blank=True)
    transaction_id = models.CharField(max_length=50, verbose_name='Идентификатор успешной транзакции', null=True,
                                      blank=True)
    refund_transaction_id = models.CharField(max_length=50, verbose_name='Идентификатор транзакции возврата',
                                             null=True, blank=True)
    currency = models.CharField(max_length=3, verbose_name='Валюта', null=True, blank=True)
    description = models.CharField(max_length=250, verbose_name='Описание', null=True, blank=True)
    card_mask = models.CharField(max_length=25, verbose_name='Маска карты', null=True, blank=True)
    terminal = models.CharField(max_length=45, verbose_name='ID терминала', null=True, blank=True)
    response_data = models.TextField(max_length=1000, verbose_name='Полученные данные', null=True,
                                     blank=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    def __str__(self):
        return f'{self.pk}-{self.ticket_sale.pk}'

    class Meta:
        verbose_name = 'Платеж заказа'
        verbose_name_plural = 'Платежи заказов'
        ordering = ['-id']


class TicketSalesTicket(LoggableModelMixin, models.Model):
    ticket_sale = models.ForeignKey(TicketSale, on_delete=models.CASCADE, verbose_name="Заказ")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Услуга")
    payment = models.ForeignKey(TicketSalesPayments, on_delete=models.PROTECT, verbose_name="Платеж", blank=True,
                                null=True)
    amount = models.IntegerField(verbose_name="Сумма билета", blank=True, null=True)
    number = models.PositiveSmallIntegerField(verbose_name="Номер билета")
    ticket_guid = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="Идентификатор билета")
    event = models.ForeignKey(Event, on_delete=models.PROTECT, verbose_name="Мероприятие")
    event_date = models.DateField(verbose_name="Дата мероприятия", default=default_datetime)
    event_time = models.TimeField(verbose_name="Время начала мероприятия")
    event_time_end = models.TimeField(verbose_name="Время окончания мероприятия", blank=True, null=True)
    last_event_code = models.CharField(max_length=1, verbose_name="Код последнего события", blank=True, null=True,
                                       default='')
    activated_date = models.DateTimeField(verbose_name="Дата активации", blank=True, null=True)
    process_id = models.CharField(max_length=20, verbose_name='Идентификатор процесса', null=True, blank=True)
    is_refund = models.BooleanField(verbose_name='Возвратный', default=False)
    refund_amount = models.IntegerField(verbose_name="Сумма возврата", blank=True, default=0)

    @property
    def payment_method(self):
        return self.payment.payment_method if self.payment else None

    def __str__(self):
        return f'{self.ticket_sale.id}-{self.number} от {self.ticket_sale.date}'

    class Meta:
        verbose_name = 'Билет в заказе'
        verbose_name_plural = 'Билеты в заказах'
        ordering = ['number']


class TicketSalesBooking(models.Model):
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Услуга")
    event = models.ForeignKey(Event, on_delete=models.PROTECT, verbose_name="Мероприятие")
    event_date = models.DateField(verbose_name="Дата мероприятия", default=default_datetime)

webapp/templates/ticket_sales/home_page_terminal.html
{% extends 'base_terminal.html' %}

{% block content %}	
    <div class="container mt-5">
        <h3>Покупка билета</h3>
        <form action="{% url 'ticket_sales:create-sale-terminal' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Купить билет</button>
        </form>
    </div>
{% endblock %}

webapp/templates/ticket_sales/ticket_sale_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удалить заказ{% endblock %}

{% block content %}
<div class="container">
    <h3>Удалить заказ №{{ object.id }}?</h3>
    <p>Вы уверены, что хотите удалить заказ №{{ object.id }} от {{ object.date }} на сумму {{ object.amount }} ₸?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'ticket_sales:ticket-sale-list' %}" class="btn btn-secondary">Отменить</a>
    </form>
</div>
{% endblock %}

webapp/templates/ticket_sales/ticket_sale_list.html
{% extends 'base.html' %}

{% block title %}Заказы{% endblock %}

{% block content %}
    <!-- Confirmation modal for deleting selected orders -->
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Подтвердите удаление</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    Вы уверены, что хотите удалить выбранные заказы?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-danger" id="confirm-delete">Удалить</button>
                </div>
            </div>
        </div>
    </div>
    
<div class="container">
    <h3>Заказы</h3>
    
    <div class="row mb-4">
        {% if perms.ticket_sales.add_ticketsale %}
            <div class="col-md-6">            
                <form action="{% url 'ticket_sales:ticket-sale-create' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Новый заказ</button>
                </form>
                <!-- Button to select unpaid orders -->
                <button type="button" class="btn btn-secondary btn-sm mt-2" id="select-unpaid">
                    Выбрать не оплаченные
                </button>
                <!-- Button to delete selected orders -->
                <button type="button" class="btn btn-danger btn-sm mt-2" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">
                    Удалить выбранные
                </button>        
            </div>
        {% endif %}
        <div class="col-md-6">
            <form method="GET" action="{% url 'ticket_sales:ticket-sale-list' %}" class="mb-4">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Поиск по номеру заказа" value="{{ request.GET.q }}">
                    <button type="submit" class="btn btn-outline-primary">Поиск</button>
                    <a href="{% url 'ticket_sales:ticket-sale-list' %}" class="btn btn-outline-danger">Отмена</a>
                </div>
            </form>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                {% if perms.ticket_sales.delete_ticketsale %}
                    <th><input type="checkbox" id="select-all"></th>
                {% endif %}
                <th>Номер</th>
                <th>Дата время</th>
                <th>Сумма</th>
                <th>Оплачено</th>
                <th>Кол-во билетов</th>
                <th>Статус</th>
                <th>Тип продажи</th>
                {% if perms.ticket_sales.change_ticketsale %}
                <th></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for sale in object_list %}
            <tr> 
                {% if perms.ticket_sales.delete_ticketsale %}
                    <td><input type="checkbox" class="order-checkbox" value="{{ sale.id }}"></td>
                {% endif %}
                <td>
                    <a href="{% url 'ticket_sales:ticket-sale-detail' sale.id %}">
                        {{ sale.id }}
                    </a>
                </td>
                <td>
                    <a href="{% url 'ticket_sales:ticket-sale-detail' sale.id %}">
                        {{ sale.date|date:"d.m.Y" }} {% if sale.time %}
                                                        {{ sale.time|date:"H:i:s" }}
                                                    {% else %}
                                                        00:00:00
                                                    {% endif %}
                    </a>
                </td>
                <td>{{ sale.amount }} ₸</td>
                <td>{{ sale.paid_amount }} ₸</td>
                <td>{{ sale.tickets_count }}</td>
                <td>{{ sale.get_status_display }}</td>
                <td>{{ sale.get_sale_type_display }}</td>
                <td>
                    {% if perms.ticket_sales.change_ticketsale %}
                    <a href="{% url 'ticket_sales:ticket-sale-update' sale.id %}" class="btn btn-sm btn-primary">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    {% endif %}
                    {% if perms.ticket_sales.delete_ticketsale %}
                    <a href="{% url 'ticket_sales:ticket-sale-delete' sale.id %}" class="btn btn-sm btn-danger">
                        <i class="bi bi-x-circle"></i>
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="text-center">Нет данных для отображения.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <nav aria-label="Пагинация">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.previous_page_number }}" aria-label="Предыдущая">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
    
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item"><a class="page-link" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
    
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.next_page_number }}" aria-label="Следующая">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>

</div>
{% endblock %}

{% block scripts %}
<script>
    // Select all checkboxes when "Select All" is clicked
    document.getElementById('select-all').addEventListener('change', function() {
        const checkboxes = document.querySelectorAll('.order-checkbox');
        checkboxes.forEach(checkbox => checkbox.checked = this.checked);
    });

    // Select unpaid orders when "Select Unpaid" is clicked
    document.getElementById('select-unpaid').addEventListener('click', function() {
        const checkboxes = document.querySelectorAll('.order-checkbox');
        checkboxes.forEach(checkbox => {
            const status = checkbox.closest('tr').querySelector('td:nth-child(7)').innerText.trim();
            if (status === 'Не оплачен' || status === 'Отменен') {
                checkbox.checked = true;
            }
        });
    });

    // Delete selected orders on modal confirmation
    document.getElementById('confirm-delete').addEventListener('click', function() {
        const selectedIds = Array.from(document.querySelectorAll('.order-checkbox:checked'))
            .map(checkbox => checkbox.value);

        if (selectedIds.length > 0) {
            fetch("{% url 'ticket_sales:bulk-delete' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ ids: selectedIds })
            })
            .then(response => {
                if (response.ok) {                                        
                    const checkboxes = document.querySelectorAll('.order-checkbox');
                    checkboxes.forEach(checkbox => checkbox.checked = false);
                    
                    location.reload(); // Refresh the page after deletion
                }
            });
        }
        else {
            alert('Нужно выбрать хотя бы один заказ на удаление')
        }
    });
</script>
{% endblock %}