webapp/references/urls.py
from django.urls import path
from .views import (event_template_create_view, event_template_update_view, event_template_list_view,
                    event_template_detail_view, event_template_delete_view,
                    EventCreateView, EventUpdateView, EventDeleteView, EventDetailView, event_times_create,
                    event_times_update, event_times_delete, EventListView,
                    InventoryListView, InventoryCreateView, InventoryUpdateView, InventoryDeleteView, InventoryDetailView,
                    ServiceListView, ServiceCreateView, ServiceUpdateView, ServiceDeleteView, ServiceDetailView,
                    event_template_service_create, event_template_service_update, event_template_service_delete
                    )

app_name = 'references'

urlpatterns = [
    # Event template
    path('event-templates/', event_template_list_view, name='event_template_list'),
    path('event-templates/create/', event_template_create_view, name='event_template_create'),
    path('event-templates/<int:pk>/', event_template_detail_view, name='event_template_detail'),
    path('event-templates/<int:pk>/edit/', event_template_update_view, name='event_template_update'),
    path('event-templates/<int:pk>/delete/', event_template_delete_view, name='event_template_delete'),

    # Event
    path('event/list/', EventListView.as_view(), name='event-list'),
    path('event/create/', EventCreateView.as_view(), name='event-create'),
    path('event/<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),

    # EventTimes
    path('event/<int:event_id>/times/create/', event_times_create, name='event-times-create'),
    path('event/<int:event_id>/times/<int:pk>/update/', event_times_update, name='event-times-update'),
    path('event/<int:event_id>/times/<int:pk>/delete/', event_times_delete, name='event-times-delete'),

    # Inventory URLs
    path('inventory/list/', InventoryListView.as_view(), name='inventory-list'),
    path('inventory/create/', InventoryCreateView.as_view(), name='inventory-create'),
    path('inventory/<int:pk>/update/', InventoryUpdateView.as_view(), name='inventory-update'),
    path('inventory/<int:pk>/delete/', InventoryDeleteView.as_view(), name='inventory-delete'),
    path('inventory/<int:pk>/', InventoryDetailView.as_view(), name='inventory-detail'),

    # Service URLs
    path('service/list/', ServiceListView.as_view(), name='service-list'),
    path('service/create/', ServiceCreateView.as_view(), name='service-create'),
    path('service/<int:pk>/update/', ServiceUpdateView.as_view(), name='service-update'),
    path('service/<int:pk>/delete/', ServiceDeleteView.as_view(), name='service-delete'),
    path('service/<int:pk>/', ServiceDetailView.as_view(), name='service-detail'),

    # EventTemplateServices
    path('event-templates/<int:event_template_id>/service/create/',
         event_template_service_create, name='event-template-service-create'),
    path('<int:event_template_id>/event-templates/service/<int:pk>/update/',
         event_template_service_update, name='event-template-service-update'),
    path('<int:event_template_id>/event-templates/service/<int:pk>/delete/',
         event_template_service_delete, name='event-template-service-delete'),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views

from references.views import home_page
from .drf_yasg_schema import schema_view

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path("references/", include("references.urls")),
    path("ticket-sales/", include("ticket_sales.urls")),
    path("reports/", include("reports.urls")),

    path('api-token-auth/', views.obtain_auth_token),
    path("api/", include("ticket_sales.api_urls")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', home_page, name='home'),
]

# # Add this to include language prefixes
# urlpatterns += i18n_patterns(
#     path('', HomePageView.as_view(), name='home'),
#     path("news/", include("news.urls")),
# )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/references/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


class EventTemplate(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    logo = models.ImageField(upload_to="logos/%Y/%m/%d", blank=True, null=True, verbose_name='Логотип')
    description = models.TextField(verbose_name="Описание", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'
        ordering = ['name']


class Event(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    event_template = models.ForeignKey(EventTemplate, on_delete=models.CASCADE, verbose_name="Шаблон мероприятий")
    begin_date = models.DateField(verbose_name="Дата начала")
    end_date = models.DateField(verbose_name="Дата окончания")
    quantity = models.PositiveSmallIntegerField(verbose_name="Количество билетов", blank=True, null=True)
    on_monday = models.BooleanField(verbose_name='Понедельник')
    on_tuesday = models.BooleanField(verbose_name='Вторник')
    on_wednesday = models.BooleanField(verbose_name='Среда')
    on_thursday = models.BooleanField(verbose_name='Четверг')
    on_friday = models.BooleanField(verbose_name='Пятница')
    on_saturday = models.BooleanField(verbose_name='Суббота')
    on_sunday = models.BooleanField(verbose_name='Воскресенье')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Сеанс мероприятия'
        verbose_name_plural = 'Сеансы мероприятий'
        ordering = ['-begin_date']


class EventTimes(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name="Мероприятие")
    begin_date = models.TimeField(verbose_name="Дата начала")
    end_date = models.TimeField(verbose_name="Дата окончания")
    is_active = models.BooleanField(verbose_name="Активность", default=True)

    def __str__(self):
        return f'{self.event.id}: {self.begin_date}-{self.end_date}'

    class Meta:
        verbose_name = 'Время сеанса мероприятия'
        verbose_name_plural = 'Время сеансов мероприятий'
        ordering = ['begin_date']


class Inventory(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    size = models.CharField(max_length=15, verbose_name="Размер")
    quantity = models.PositiveSmallIntegerField(verbose_name="Количество")
    cost = models.IntegerField(verbose_name="Стоимость")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Инвентарь'
        verbose_name_plural = 'Инвентарь'
        ordering = ['name']


class SaleType(models.Model):
    code = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    cost = models.IntegerField(verbose_name="Стоимость")
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, verbose_name="Инвентарь", null=True, blank=True)
    on_calculation = models.BooleanField(verbose_name="Учитывать в подсчете билетов", default=False)
    sale_types = models.ManyToManyField(SaleType, verbose_name='Виды продаж', default=None)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'
        ordering = ['name']


class EventTemplateServices(models.Model):
    event_template = models.ForeignKey(EventTemplate, on_delete=models.CASCADE, verbose_name="Мероприятие")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Услуга")

    def __str__(self):
        return f'{self.event_template.name} / {self.service.name} ({self.id})'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['event_template', 'service'],
                name='unique_service_per_event_template'
            )
        ]
        verbose_name = 'Услуга в мероприятии'
        verbose_name_plural = 'Услуги в мероприятиях'

webapp/references/forms.py
from django import forms
from django.forms import inlineformset_factory, CheckboxSelectMultiple
from crispy_forms.bootstrap import InlineField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit, Fieldset, ButtonHolder, Field, Div

from .models import EventTemplate, Event, EventTimes, Inventory, Service, EventTemplateServices, SaleType


class EventTemplateForm(forms.ModelForm):
    class Meta:
        model = EventTemplate
        fields = ['name', 'logo', 'description']

    def __init__(self, *args, **kwargs):
        super(EventTemplateForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'style': 'height:70px;'})

    def clean_name(self):
        name = self.cleaned_data['name']
        # Check for duplicate names
        if EventTemplate.objects.filter(name=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f"Мероприятие с наименованием '{name}' уже существует.")
        return name


class EventForm(forms.ModelForm):
    begin_date = forms.DateField(
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        input_formats=['%Y-%m-%d'],
        label='Дата начала'
    )
    end_date = forms.DateField(
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
        input_formats=['%Y-%m-%d'],
        label='Дата окончания'
    )

    class Meta:
        model = Event
        fields = ['name', 'event_template', 'begin_date', 'end_date', 'quantity', 'on_monday', 'on_tuesday',
                  'on_wednesday', 'on_thursday', 'on_friday', 'on_saturday', 'on_sunday']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'event_template',
            'begin_date',
            'end_date',
            'quantity',
            Row(
                Div(Field('on_monday'), css_class='d-none'),  # Скрываем поля в общем рендере
                Div(Field('on_tuesday'), css_class='d-none'),
                Div(Field('on_wednesday'), css_class='d-none'),
                Div(Field('on_thursday'), css_class='d-none'),
                Div(Field('on_friday'), css_class='d-none'),
                Div(Field('on_saturday'), css_class='d-none'),
                Div(Field('on_sunday'), css_class='d-none'),
            ),
        )

    def clean_name(self):
        name = self.cleaned_data['name']
        # Check for duplicate names
        if Event.objects.filter(name=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f"Сеанс мероприятия с наименованием '{name}' уже существует.")
        return name


class EventTimesForm(forms.ModelForm):
    begin_date = forms.TimeField(
        widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
        input_formats=['%H:%M'],
        label='Время начала'
    )
    end_date = forms.TimeField(
        widget=forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
        input_formats=['%H:%M'],
        label='Время окончания'
    )

    class Meta:
        model = EventTimes
        fields = ['begin_date', 'end_date', 'is_active']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_active'].widget.attrs.update({'class': 'form-check-input'})


class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['name', 'size', 'quantity', 'cost']

    def clean_name(self):
        name = self.cleaned_data['name']
        # Check for duplicate names
        if Inventory.objects.filter(name=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f"Инвентарь с наименованием '{name}' уже существует.")
        return name


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'cost', 'inventory', 'on_calculation', 'sale_types']
        widgets = {
            'sale_types': CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # If the form is used for creating a new instance (no initial sale types)
        if not self.instance.pk:
            # Set all SaleType instances as initial value
            self.fields['sale_types'].initial = SaleType.objects.all()

    def clean_name(self):
        name = self.cleaned_data['name']
        # Check for duplicate names
        if Service.objects.filter(name=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f"Услуга с наименованием '{name}' уже существует.")
        return name


class EventTemplateServicesForm(forms.ModelForm):
    class Meta:
        model = EventTemplateServices
        fields = ['service',]

    def __init__(self, *args, **kwargs):
        self.event_template = kwargs.pop('event_template', None)  # Capture the event template
        super().__init__(*args, **kwargs)
        self.fields['service'].widget.attrs.update({'class': 'form-control'})

    def clean(self):
        cleaned_data = super().clean()
        service = cleaned_data.get('service')

        # Check for duplicate services within the same event template
        if EventTemplateServices.objects.filter(
            event_template=self.event_template,
            service=service
        ).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f"Услуга '{service}' уже добавлена в мероприятие.")

        return cleaned_data

webapp/templates/references/event_confirm_delete.html
{% extends "base.html" %}

{% block title %}Мероприятие{% endblock %}
{% block content %}
    <div class="container">
        <h3>Вы уверены, что хотите удалить мероприятие "{{ event.event_template.name }}"?</h3>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Да, удалить</button>
            <a href="{% url 'references:event-list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

webapp/templates/references/event_detail.html
{% extends "base.html" %}

{% block title %}Сеанс мероприятия{% endblock %}
{% block content %}
    <div class="container mt-4">
        <h3>{{ object.name }}</h3>
        <p>Начало: {{ object.begin_date }}</p>
        <p>Окончание: {{ object.end_date }}</p>
        <p>Количество билетов: {{ object.quantity }}</p>

        <div class="mb-3">
            <div class="form-check form-check-inline"
                style="color:{% if object.on_monday %} green {% else %} red {% endif %}">
                Пн
            </div>
            <div class="form-check form-check-inline"
                style="color:{% if object.on_tuesday %} green {% else %} red {% endif %}">
                Вт
            </div>
            <div class="form-check form-check-inline" 
                 style="color:{% if object.on_wednesday %} green {% else %} red {% endif %}">
                Ср 
            </div>
            <div class="form-check form-check-inline"
                style="color:{% if object.on_thursday %} green {% else %} red {% endif %}">
                Чт
            </div>
            <div class="form-check form-check-inline"
                style="color:{% if object.on_friday %} green {% else %} red {% endif %}">
                Пт
            </div>
            <div class="form-check form-check-inline"
                style="color:{% if object.on_saturday %} green {% else %} red {% endif %}">
                Сб
            </div>
            <div class="form-check form-check-inline"
                style="color:{% if object.on_sunday %} green {% else %} red {% endif %}">
                Вс
            </div>
        </div>
        
        <h4>Время</h4>
        <div id="event-times-list">
            {% include 'references/partials/event_times_list_view.html' with event=object %}
        </div>

        <div class="mt-2">
            {% if perms.references.change_event %}
                <a href="{% url 'references:event-update' object.id %}" class="btn btn-primary">Изменить</a>
            {% endif %}
            <a href="{% url 'references:event-list' %}" class="btn btn-secondary">Закрыть</a>
        </div>
    </div>
{% endblock %}

webapp/templates/references/event_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Сеанс мероприятий{% endblock %}

{% block header %}
    <style>
        .form-check-inline {
            display: inline-block;
            margin-right: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h3>{% if object %}Редактирование{% else %}Создание{% endif %} сеанса мероприятия</h3>
        <form method="post" hx-post="
                {% if object %}{{ object.get_update_url }}{% else %}{% url 'references:event-create' %}{% endif %}"
              hx-target="body" hx-swap="outerHTML">
            {% csrf_token %}
            {{ form.name|as_crispy_field }}
            {{ form.event_template|as_crispy_field }}
            <div class="mb-3">
                <div class="form-check-inline">
                    {{ form.begin_date|as_crispy_field }}
                </div>
                <div class="form-check-inline">
                    {{ form.end_date|as_crispy_field }}
                </div>
                <div class="form-check-inline">
                    {{ form.quantity|as_crispy_field }}
                </div>
            </div>

            <div class="mb-3">
                <div class="form-check form-check-inline">
                    {{ form.on_monday.label_tag }} {{ form.on_monday }}
                </div>
                <div class="form-check form-check-inline">
                    {{ form.on_tuesday.label_tag }} {{ form.on_tuesday }}
                </div>
                <div class="form-check form-check-inline">
                    {{ form.on_wednesday.label_tag }} {{ form.on_wednesday }}
                </div>
                <div class="form-check form-check-inline">
                    {{ form.on_thursday.label_tag }} {{ form.on_thursday }}
                </div>
                <div class="form-check form-check-inline">
                    {{ form.on_friday.label_tag }} {{ form.on_friday }}
                </div>
                <div class="form-check form-check-inline">
                    {{ form.on_saturday.label_tag }} {{ form.on_saturday }}
                </div>
                <div class="form-check form-check-inline">
                    {{ form.on_sunday.label_tag }} {{ form.on_sunday }}
                </div>
            </div>

            <h4>Время</h4>
            <div id="event-times-list">
                {% if object %}
                    {% include 'references/partials/event_times_list.html' with event=object %}
                {% endif %}
            </div>

            <div class="mt-2">                
                <button type="button" class="btn btn-outline-primary"
                        hx-get="{% if object %}{% url 'references:event-times-create' object.id %}{% else %}#{% endif %}"
                        hx-target="#modal-body-content"
                        hx-swap="innerHTML"
                        hx-trigger="click" data-bs-toggle="modal" data-bs-target="#editTimeModal" 
                        {% if not object %} disabled {% endif %}>
                    Добавить время
                </button>
                
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'references:event-list' %}" class="btn btn-secondary">Закрыть</a>
            </div>
        </form>

        <!-- Модальное окно для формы добавления времени -->
        <div class="modal fade" id="editTimeModal" tabindex="-1" aria-labelledby="editTimeModalLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-lg"> <!-- Размер окна изменен на modal-lg -->
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editTimeModalLabel">Время</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="modal-body-content">
                        <!-- Сюда будет загружена форма с помощью HTMX -->
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block scripts %}
    <script>
        
    </script>
{% endblock %}

webapp/templates/references/event_list.html
{% extends "base.html" %}

{% block title %}Сеансы мероприятий{% endblock %}
{% block content %}
    <div class="container">
        <h3>Сеансы мероприятий</h3>
        {% if perms.references.add_event %}
            <a href="{% url 'references:event-create' %}" class="btn btn-primary mb-3">Добавить сеанс мероприятия</a>
        {% endif %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Наименование</th>
                <th>Дата начала</th>
                <th>Дата окончания</th>
                {% if perms.references.change_event %}
                    <th></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for event in object_list %}
                <tr>
                    <td>{{ event.id }}</td>
                    <td><a href="{% url 'references:event-detail' event.pk %}">
                        {{ event.name }}
                    </a></td>
                    <td>{{ event.begin_date }}</td>
                    <td>{{ event.end_date }}</td>
                    <td>
                        {% if perms.references.change_event %}
                            <a href="{% url 'references:event-update' event.pk %}" class="btn btn-primary btn-sm"><i class="bi bi-pencil-square"></i></a>
                        {% endif %}
                        {% if perms.references.delete_event %}
                            <a href="{% url 'references:event-delete' event.pk %}" class="btn btn-danger btn-sm"><i class="bi bi-x-circle"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

webapp/templates/references/event_template_detail.html
{% extends "base.html" %}

{% block title %}Мероприятие{% endblock %}
{% block content %}
    <div class="container">
        <h3>{{ event_template.name }}</h3>
        {% if event_template.logo %}
            <img src="{{ event_template.logo.url }}" alt="Logo" class="img-fluid mb-3">
        {% endif %}
        <p>{{ event_template.description }}</p>

        <!-- Раздел для работы с EventTemplateServices -->
        <h4 class="mt-4">Доступные услуги</h4>
        <div id="event-template-services-list">            
            {% include 'references/partials/event_template_services_list_view.html' with event_template=event_template %}            
        </div>
        
        {% if perms.references.change_eventtemplate %}
            <a href="{% url 'references:event_template_update' event_template.id %}" class="btn btn-primary">Изменить</a>
        {% endif %}
        <a href="{% url 'references:event_template_list' %}" class="btn btn-secondary">Закрыть</a>
    </div>
{% endblock %}

webapp/templates/references/event_template_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load form_filters %}

{% block title %}Мероприятие{% endblock %}

{% block content %}
    <div class="container">
        <h3>{% if form.instance.pk %}Редактирование{% else %}Создание{% endif %} мероприятия</h3>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.name|as_crispy_field }}
                {{ form.logo|as_crispy_field }}
            </div>
            <div>
                {{ form.description|as_crispy_field }}
            </div>

            <hr class="my-3">
            <!-- Раздел для работы с EventTemplateServices -->
            <h4 class="mt-4">Доступные услуги</h4>
            <div id="event-template-services-list">
                {% if form.instance.pk %}
                    {% include 'references/partials/event_template_services_list.html' with event_template=form.instance %}
                {% endif %}
            </div>

            {% if form.instance.pk %}
                <!-- Кнопка для добавления услуги -->
                <button type="button" class="btn btn-outline-primary" id="add-service-button"
                        hx-get="{% url 'references:event-template-service-create' form.instance.pk %}"
                        hx-target="#modal-body-content"
                        hx-trigger="click" data-bs-toggle="modal" data-bs-target="#editServiceModal">
                    Добавить услугу
                </button>
            {% else %}
                Для добавления услуги необходимо сохранить мероприятие
            {% endif %}

            <hr class="my-3">
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'references:event_template_list' %}" class="btn btn-secondary">Закрыть</a>
            </div>
        </form>

        <!-- Модальное окно для форм (создание/редактирование/удаление) -->
        <div class="modal fade" id="editServiceModal" tabindex="-1" aria-labelledby="editServiceModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editServiceModalLabel">Услуга</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="modal-body-content">
                        <!-- Сюда будет загружена форма с помощью HTMX -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/references/event_template_list.html
{% extends "base.html" %}

{% block title %}Мероприятия{% endblock %}
{% block content %}
    <div class="container">
        <h3>Мероприятия</h3>
        {% if perms.references.add_eventtemplate %}
            <a href="{% url 'references:event_template_create' %}" class="btn btn-primary mb-3">Добавить мероприятие</a>
        {% endif %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Название</th>
                <th>Логотип</th>
                <th>Описание</th>
                {% if perms.references.change_eventtemplate %}
                    <th></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for template in event_templates %}
                <tr>
                    <td><a href="{% url 'references:event_template_detail' template.pk %}">
                        {{ template.name }}
                    </a>
                    </td>
                    <td>
                        {% if template.logo %}
                        <img src="{{ template.logo.url }}" alt="Logo" width="50">
                        {% else %}
                        no photo
                        {% endif %}
                    </td>
                    <td>{{ template.description }}</td>
                    <td>
                        {% if perms.references.change_eventtemplate %}
                            <a href="{% url 'references:event_template_update' template.pk %}" class="btn btn-primary btn-sm"><i class="bi bi-pencil-square"></i></a>
                        {% endif %}
                        {% if perms.references.delete_eventtemplate %}
                            <a href="{% url 'references:event_template_delete' template.pk %}" class="btn btn-danger btn-sm"><i class="bi bi-x-circle"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

webapp/templates/references/inventory_detail.html
{% extends 'base.html' %}

{% block title %}Информация о инвентаре{% endblock %}

{% block content %}
<div class="container mt-4">
    <h3>{{ object.name }}</h3>
    <p>Мероприятие: {{ object.event.name }}</p>
    <p>Размер: {{ object.size }}</p>
    <p>Количество: {{ object.quantity }}</p>
    <p>Стоимость: {{ object.cost }}</p>
    {% if perms.references.change_inventory %}
        <a href="{% url 'references:inventory-update' object.id %}" class="btn btn-primary">Изменить</a>
    {% endif %}
    <a href="{% url 'references:inventory-list' %}" class="btn btn-secondary">Закрыть</a>
</div>
{% endblock %}

webapp/templates/references/service_detail.html
{% extends 'base.html' %}

{% block title %}Информация об услуге{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h3>{{ object.name }}</h3>
        <p>Наименование: {{ object.name }}</p>
        <p>Стоимость: {{ object.cost }}</p>
        <p>Инвентарь: {{ object.inventory }}</p>
        <div>Учитывается в подсчете билетов:  {% if object.on_calculation %}
                <strong class="text-success">Да</strong>
            {% else %}
                <strong class="text-danger">Нет</strong>
            {% endif %}
        </div>
    
        <!-- Display associated sale types -->
        <div class="mt-3">
            <p>Виды продаж:</p>
            <ul>
                {% for sale_type in object.sale_types.all %}
                    <li>{{ sale_type.name }}</li>
                {% empty %}
                    <li><em>Виды продаж не указаны</em></li>
                {% endfor %}
            </ul>
        </div>
        
        <div class="mt-2">
            {% if perms.references.change_service %}
                <a href="{% url 'references:service-update' object.id %}" class="btn btn-primary">Изменить</a>
            {% endif %}
            <a href="{% url 'references:service-list' %}" class="btn btn-secondary">Закрыть</a>
        </div>
    </div>
{% endblock %}