webapp/references/urls.py
from django.urls import path
from .views import (event_template_create_view, event_template_update_view, event_template_list_view,
                    event_template_detail_view, event_template_delete_view,
                    EventCreateView, EventUpdateView, EventDeleteView, EventDetailView, event_times_create,
                    event_times_update, event_times_delete, EventListView,
                    InventoryListView, InventoryCreateView, InventoryUpdateView, InventoryDeleteView, InventoryDetailView,
                    ServiceListView, ServiceCreateView, ServiceUpdateView, ServiceDeleteView, ServiceDetailView,
                    event_template_service_create, event_template_service_update, event_template_service_delete
                    )

app_name = 'references'

urlpatterns = [
    # Event template
    path('event-templates/', event_template_list_view, name='event_template_list'),
    path('event-templates/create/', event_template_create_view, name='event_template_create'),
    path('event-templates/<int:pk>/', event_template_detail_view, name='event_template_detail'),
    path('event-templates/<int:pk>/edit/', event_template_update_view, name='event_template_update'),
    path('event-templates/<int:pk>/delete/', event_template_delete_view, name='event_template_delete'),

    # Event
    path('event/list/', EventListView.as_view(), name='event-list'),
    path('event/create/', EventCreateView.as_view(), name='event-create'),
    path('event/<int:pk>/update/', EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),

    # EventTimes
    path('event/<int:event_id>/times/create/', event_times_create, name='event-times-create'),
    path('event/<int:event_id>/times/<int:pk>/update/', event_times_update, name='event-times-update'),
    path('event/<int:event_id>/times/<int:pk>/delete/', event_times_delete, name='event-times-delete'),

    # Inventory URLs
    path('inventory/list/', InventoryListView.as_view(), name='inventory-list'),
    path('inventory/create/', InventoryCreateView.as_view(), name='inventory-create'),
    path('inventory/<int:pk>/update/', InventoryUpdateView.as_view(), name='inventory-update'),
    path('inventory/<int:pk>/delete/', InventoryDeleteView.as_view(), name='inventory-delete'),
    path('inventory/<int:pk>/', InventoryDetailView.as_view(), name='inventory-detail'),

    # Service URLs
    path('service/list/', ServiceListView.as_view(), name='service-list'),
    path('service/create/', ServiceCreateView.as_view(), name='service-create'),
    path('service/<int:pk>/update/', ServiceUpdateView.as_view(), name='service-update'),
    path('service/<int:pk>/delete/', ServiceDeleteView.as_view(), name='service-delete'),
    path('service/<int:pk>/', ServiceDetailView.as_view(), name='service-detail'),

    # EventTemplateServices
    path('event-templates/<int:event_template_id>/service/create/',
         event_template_service_create, name='event-template-service-create'),
    path('<int:event_template_id>/event-templates/service/<int:pk>/update/',
         event_template_service_update, name='event-template-service-update'),
    path('<int:event_template_id>/event-templates/service/<int:pk>/delete/',
         event_template_service_delete, name='event-template-service-delete'),
]

webapp/reports/urls.py
# urls.py
from django.urls import path
from .views import tickets_report, sales_report, sessions_report, sales_report_export, export_sessions_report_to_excel, \
    export_tickets_report_to_excel, ticket_print_data, ticket_print_pdf, services_report, services_report_excel_export

app_name = 'reports'

urlpatterns = [
    path('sales/', sales_report, name='sales_report'),
    path('sales-export/', sales_report_export, name='sales_report_export'),
    path('sessions/', sessions_report, name='sessions_report'),
    path('sessions-export/', export_sessions_report_to_excel, name='sessions_report_export'),
    path('tickets/', tickets_report, name='tickets_report'),
    path('tickets-export/', export_tickets_report_to_excel, name='tickets_report_export'),
    path('ticket-print-data/<int:ticket_id>/', ticket_print_data, name='ticket-print-data'),
    path('ticket-print-pdf/<int:ticket_id>/', ticket_print_pdf, name='ticket-print-pdf'),
    path('services/', services_report, name='services_report'),
    path('services-export/', services_report_excel_export, name='services_report_export'),
]

webapp/ticket_sales/urls.py
from django.urls import path
from .views import TicketSaleListView, TicketSaleUpdateView, TicketSaleDeleteView, \
    TicketSaleDetailView, payment_process_cashier, check_payment_status_cashier, payment_detail_view, \
    ticket_sale_create_view, \
    ticket_sale_update_view, cash_payment_process, print_ticket_view, filtered_events, filtered_event_times, \
    ticket_sales_service_create, ticket_sales_service_update, ticket_sales_service_delete, \
    ticket_sales_payments_create, ticket_sales_payments_update, ticket_sales_payments_delete, \
    filtered_services, get_service_cost, terminal_settings_cashier, register_terminal, refresh_terminal_token, \
    get_events_dates, get_events, TicketSaleUpdateViewTerminal, home_page_terminal, create_ticket_sale_terminal, \
    create_ticket_sale_cashier, payment_process_terminal, check_payment_status_terminal, terminal_settings_terminal, \
    get_refund_tickets, refund_tickets, kiosk_sale_tickets, ticket_sales_booking_list, ticket_sales_booking_create, \
    ticket_sales_booking_update, ticket_sales_booking_delete, tickets_purchased, delete_bookings, get_refund_payments, \
    check_payment_refund_status, bulk_delete_ticket_sales, ticket_sales_create_discount_tickets

app_name = 'ticket_sales'

urlpatterns = [
    path('list/', TicketSaleListView.as_view(), name='ticket-sale-list'),
    path('create/', create_ticket_sale_cashier, name='ticket-sale-create'),
    path('<int:pk>/update/', TicketSaleUpdateView.as_view(), name='ticket-sale-update'),
    path('<int:pk>/delete/', TicketSaleDeleteView.as_view(), name='ticket-sale-delete'),
    path('bulk-delete/', bulk_delete_ticket_sales, name='bulk-delete'),
    path('<int:pk>/', TicketSaleDetailView.as_view(), name='ticket-sale-detail'),
    path('create-x/', ticket_sale_create_view, name='ticket-sale-create-x'),
    path('<int:pk>/update-x/', ticket_sale_update_view, name='ticket-sale-update-x'),
    path('<int:pk>/update-t/', TicketSaleUpdateViewTerminal.as_view(), name='ticket-sale-update-t'),
    path('home-terminal/', home_page_terminal, name='home-terminal'),
    path('kiosk-sale-tickets/<uuid:kiosk_guid>/', kiosk_sale_tickets, name='kiosk-sale-tickets'),
    path('tickets-purchased/<int:sale_id>/', tickets_purchased, name='tickets-purchased'),
    path('create-sale-terminal/', create_ticket_sale_terminal, name='create-sale-terminal'),
    path('delete-bookings/', delete_bookings, name='delete-bookings'),

    # TicketSalesService URLs
    path('<int:ticket_sale_id>/services/create/', ticket_sales_service_create,
         name='ticket-sales-service-create'),
    path('<int:ticket_sale_id>/services/<int:pk>/update/', ticket_sales_service_update,
         name='ticket-sales-service-update'),
    path('<int:ticket_sale_id>/services/<int:pk>/delete/', ticket_sales_service_delete,
         name='service-delete'),

    # TicketSalesPayments URLs
    path('<int:ticket_sale_id>/payments/<int:pk>/detail', payment_detail_view, name='payment-detail'),
    path('<int:ticket_sale_id>/payments/create/', ticket_sales_payments_create, name='payment-create'),
    path('<int:ticket_sale_id>/payments/<int:pk>/update/', ticket_sales_payments_update,
         name='payment-update'),
    path('<int:ticket_sale_id>/payments/<int:pk>/delete/', ticket_sales_payments_delete,
         name='payment-delete'),

    # Payment process
    path('payment-process/<int:ticket_sale_id>/', payment_process_cashier, name='payment-process'),
    path('payment-process-terminal/<int:ticket_sale_id>/', payment_process_terminal, name='payment-process-terminal'),
    path('check-payment-status/<str:process_id>/<str:ticket_sale_id>/<str:expected_amount>',
         check_payment_status_cashier,
         name='check-payment-status'),
    path('check-payment-status-terminal/<str:process_id>/<str:ticket_sale_id>/<str:expected_amount>/',
         check_payment_status_terminal,
         name='check-payment-status-terminal'),
    path('cash-payment-process/<int:ticket_sale_id>/', cash_payment_process, name='cash-payment-process'),

    # Print ticket
    path('ticket-print-data/<int:ticket_sale_id>/', print_ticket_view, name='ticket-print-data'),

    # Filtered events, services
    path('filtered-events/', filtered_events, name='filtered-events'),
    path('filtered-event-times/', filtered_event_times, name='filtered-event-times'),
    path('filtered-services/<str:sale_type>/', filtered_services, name='filtered-services'),
    path('get-service-cost/', get_service_cost, name='get-service-cost'),
    path('get-events-dates/', get_events_dates, name='get-events-dates'),
    path('get-events/', get_events, name='get-events'),

    # Terminal settings
    path('terminal-settings-cashier/', terminal_settings_cashier, name='terminal-settings-cashier'),
    path('terminal-settings-terminal/', terminal_settings_terminal, name='terminal-settings-terminal'),
    path('register-terminal/', register_terminal, name='register-terminal'),
    path('refresh-terminal-token/', refresh_terminal_token, name='refresh-terminal-token'),

    # Возврат билетов
    path('<int:sale_id>/refund-tickets/', get_refund_tickets, name='refund_tickets_list'),
    path('<int:sale_id>/refund-tickets/confirm/', refund_tickets, name='refund_tickets'),
    path('check-refund-status/<str:process_id>/<str:ticket_sale_id>/', check_payment_refund_status,
         name='check-refund-status'),

    # Бронирование билетов
    path('bookings/<uuid:booking_guid>/', ticket_sales_booking_list, name='booking_list'),
    path('bookings/create/', ticket_sales_booking_create, name='booking_create'),
    path('bookings/<int:pk>/edit/', ticket_sales_booking_update, name='booking_update'),
    path('bookings/<int:pk>/delete/', ticket_sales_booking_delete, name='booking_delete'),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views

from references.views import home_page
from .drf_yasg_schema import schema_view

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path("references/", include("references.urls")),
    path("ticket-sales/", include("ticket_sales.urls")),
    path("reports/", include("reports.urls")),

    path('api-token-auth/', views.obtain_auth_token),
    path("api/", include("ticket_sales.api_urls")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', home_page, name='home'),
]

# # Add this to include language prefixes
# urlpatterns += i18n_patterns(
#     path('', HomePageView.as_view(), name='home'),
#     path("news/", include("news.urls")),
# )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/references/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


class EventTemplate(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    logo = models.ImageField(upload_to="logos/%Y/%m/%d", blank=True, null=True, verbose_name='Логотип')
    description = models.TextField(verbose_name="Описание", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'
        ordering = ['name']


class Event(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    event_template = models.ForeignKey(EventTemplate, on_delete=models.CASCADE, verbose_name="Шаблон мероприятий")
    begin_date = models.DateField(verbose_name="Дата начала")
    end_date = models.DateField(verbose_name="Дата окончания")
    quantity = models.PositiveSmallIntegerField(verbose_name="Количество билетов", blank=True, null=True)
    on_monday = models.BooleanField(verbose_name='Понедельник')
    on_tuesday = models.BooleanField(verbose_name='Вторник')
    on_wednesday = models.BooleanField(verbose_name='Среда')
    on_thursday = models.BooleanField(verbose_name='Четверг')
    on_friday = models.BooleanField(verbose_name='Пятница')
    on_saturday = models.BooleanField(verbose_name='Суббота')
    on_sunday = models.BooleanField(verbose_name='Воскресенье')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Сеанс мероприятия'
        verbose_name_plural = 'Сеансы мероприятий'
        ordering = ['-begin_date']


class EventTimes(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name="Мероприятие")
    begin_date = models.TimeField(verbose_name="Дата начала")
    end_date = models.TimeField(verbose_name="Дата окончания")
    is_active = models.BooleanField(verbose_name="Активность", default=True)

    def __str__(self):
        return f'{self.event.id}: {self.begin_date}-{self.end_date}'

    class Meta:
        verbose_name = 'Время сеанса мероприятия'
        verbose_name_plural = 'Время сеансов мероприятий'
        ordering = ['begin_date']


class Inventory(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    size = models.CharField(max_length=15, verbose_name="Размер")
    quantity = models.PositiveSmallIntegerField(verbose_name="Количество")
    cost = models.IntegerField(verbose_name="Стоимость")

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Инвентарь'
        verbose_name_plural = 'Инвентарь'
        ordering = ['name']


class SaleType(models.Model):
    code = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=300, verbose_name='Наименование')
    cost = models.IntegerField(verbose_name="Стоимость")
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, verbose_name="Инвентарь", null=True, blank=True)
    on_calculation = models.BooleanField(verbose_name="Учитывать в подсчете билетов", default=False)
    sale_types = models.ManyToManyField(SaleType, verbose_name='Виды продаж', default=None)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'
        ordering = ['name']


class EventTemplateServices(models.Model):
    event_template = models.ForeignKey(EventTemplate, on_delete=models.CASCADE, verbose_name="Мероприятие")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="Услуга")

    def __str__(self):
        return f'{self.event_template.name} / {self.service.name} ({self.id})'

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['event_template', 'service'],
                name='unique_service_per_event_template'
            )
        ]
        verbose_name = 'Услуга в мероприятии'
        verbose_name_plural = 'Услуги в мероприятиях'

webapp/templates/site/header.html
<header class="bg-light py-2 px-3 d-flex justify-content-between align-items-center border-bottom"
        style="position: fixed; top: 0; width: 100%; z-index: 1030;">
    <div class="d-flex align-items-center">
        <a class="navbar-brand h5 mb-0" href="{% url 'home' %}">АРМ Касса</a>
    </div>

    <div class="flex-grow-1 mx-3">
        <div id="main-progress-bar" class="progress d-none" style="height: 25px;">
            <div class="progress-bar progress-bar-striped progress-bar-animated"
                 role="progressbar"
                 style="width: 100%">
                <span id="progress-bar-text">Соединение с терминалом...</span>
            </div>
        </div>
    </div>

    <div>
        {% if user.is_authenticated %}
            <span>Привет, {{ user.username }}!</span>
            <a class="btn btn-outline-primary btn-sm ms-3" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="btn btn-outline-primary btn-sm" href="{% url 'login' %}">Авторизация</a>
        {% endif %}
    </div>
</header>

webapp/templates/site/home.html
{% extends "base.html" %}

{% block title %}Главная{% endblock %}
{% block content %}
    <div class="container">
        <h1>Главная страница</h1>
        <p>Добро пожаловать!</p>
    </div>
{% endblock %}

webapp/templates/site/navbar.html
<div style="max-width: 250px; padding-top: 40px;">
<nav class="vertical-nav">
    <ul class="nav flex-column">

    {% if perms.ticket_sales.view_ticketsale %}
    <li class="part-nav-item">
        <a href="{% url 'ticket_sales:ticket-sale-list' %}"
        class="nav-link razdel {% if 'ticket-sales' in request.path and not 'terminal' in request.path %}active{% endif %}">
            <i class="bi bi-ticket-perforated-fill me-2"></i>Заказы
        </a>
    </li>
    {% endif %}
    
    {% if perms.references.view_eventtemplate or perms.references.view_event or perms.references.view_inventory or perms.references.view_service %}
    <li class="part-nav-item">
        <a class="nav-link razdel disabled" href="#">Справочники</a>

        <ul class="nav flex-column nested-nav">
            {% if perms.references.view_eventtemplate %}
            <li class="nav-item">
                <a href="{% url 'references:event_template_list' %}"
                class="nav-link {% if 'references/event-template' in request.path %}active{% endif %}">
                    <i class="bi bi-file-earmark-text-fill me-2"></i> Мероприятия
                </a>
            </li>
            {% endif %}

            {% if perms.references.view_event %}
            <li class="nav-item">
                <a href="{% url 'references:event-list' %}"
                class="nav-link {% if 'references/event' in request.path and not 'event-template' in request.path %}active{% endif %}">
                    <i class="bi bi-calendar-event me-2"></i> Сеансы мероприятий
                </a>
            </li>
            {% endif %}

            {% if perms.references.view_inventory %}
            <li class="nav-item">
                <a href="{% url 'references:inventory-list' %}"
                class="nav-link {% if 'references/inventory' in request.path %}active{% endif %}">
                    <i class="bi bi-box-seam-fill me-2"></i> Инвентарь
                </a>
            </li>
            {% endif %}

            {% if perms.references.view_service %}
            <li class="nav-item">
                <a href="{% url 'references:service-list' %}"
                class="nav-link {% if 'references/service' in request.path %}active{% endif %}">
                    <i class="bi bi-wrench me-2"></i> Услуги
                </a>
            </li>
            {% endif %}
        </ul>    
    </li>
    {% endif %}
    
    {% if perms.reports.view_sales_report or perms.reports.view_events_report or perms.reports.view_tickets_report or perms.reports.view_services_report %}
    <li class="part-nav-item">
        <a class="nav-link razdel disabled" href="#">Отчеты</a>

        <ul class="nav flex-column nested-nav">
            {% if perms.reports.view_sales_report %}
                <li class="nav-item">
                    <a href="{% url 'reports:sales_report' %}?start_date={% now 'd-m-Y' %}&end_date={% now 'd-m-Y' %}"
                    class="nav-link {% if '/reports/sales/' in request.path %}active{% endif %}">
                        <i class="bi bi-file-earmark-spreadsheet"></i> Отчет продажи
                    </a>
                </li>
            {% endif %}

            {% if perms.reports.view_events_report %}
                <li class="nav-item">
                    <a href="{% url 'reports:sessions_report' %}?start_date={% now 'd-m-Y' %}&end_date={% now 'd-m-Y' %}"
                    class="nav-link {% if '/reports/sessions/' in request.path %}active{% endif %}">
                        <i class="bi bi-file-earmark-spreadsheet"></i> Отчет по сеансам
                    </a>
                </li>
            {% endif %}

            {% if perms.reports.view_tickets_report %}
                <li class="nav-item">
                    <a href="{% url 'reports:tickets_report' %}?start_date={% now 'd-m-Y' %}&end_date={% now 'd-m-Y' %}"
                    class="nav-link {% if '/reports/tickets/' in request.path %}active{% endif %}">
                        <i class="bi bi-file-earmark-spreadsheet"></i> Отчет Реестр билетов
                    </a>
                </li>
            {% endif %}

            {% if perms.reports.view_services_report %}
                <li class="nav-item">
                    <a href="{% url 'reports:services_report' %}?start_date={% now 'd-m-Y' %}&end_date={% now 'd-m-Y' %}"
                    class="nav-link {% if '/reports/services/' in request.path %}active{% endif %}">
                        <i class="bi bi-file-earmark-spreadsheet"></i> Отчет Реестр видов услуг
                    </a>
                </li>
            {% endif %}
        </ul>
    </li>
    {% endif %}

    {% if perms.ticket_sales.change_terminalsettings %}
    <li class="part-nav-item">
        <a class="nav-link razdel disabled" href="#">Настройки</a>
        
        <ul class="nav flex-column nested-nav">            
            <li class="nav-item">
                <a href="{% url 'ticket_sales:terminal-settings-cashier' %}"
                class="nav-link {% if 'terminal-settings-cashier' in request.path %}active{% endif %}">
                    <i class="bi bi-gear-wide-connected"></i> Настройки терминала для кассира
                </a>
            </li>
                
            <li class="nav-item">
                <a href="{% url 'ticket_sales:terminal-settings-terminal' %}"
                class="nav-link {% if 'terminal-settings-terminal' in request.path %}active{% endif %}">
                    <i class="bi bi-gear-wide-connected"></i> Настройки терминала для киоска
                </a>        
            </li>            
        </ul>
    </li>
    {% endif %}

    </ul>
</nav>
</div>